"""accounts run diagnostics targets extras

Revision ID: c303ac031ac1
Revises: 44651d6635f4
Create Date: 2026-07-22 09:35:01.247551
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c303ac031ac1'
down_revision: Union[str, None] = '44651d6635f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('profile_slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('never', 'connected', 'expired', 'verification_required', 'error', name='accountstatus'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('encrypted_state', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_slug')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_status'), ['status'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diagnostic_path', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('session_status', sa.String(length=40), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('pending', 'running', 'success', 'failed', 'skipped', 'suspended', name='runstatus'),
               existing_nullable=False)

    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        # server_default : rétro-remplit les cibles déjà en base (sinon NOT NULL
        # échoue sur les lignes existantes). Les nouvelles cibles utilisent le
        # défaut Python du modèle.
        batch_op.add_column(sa.Column('capture_mode', sa.Enum('desktop', 'mobile', name='capturemode'), nullable=False, server_default='desktop'))
        batch_op.add_column(sa.Column('retry_backoff_seconds', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_targets_account_id'), ['account_id'], unique=False)
        batch_op.create_foreign_key('fk_targets_account_id', 'accounts', ['account_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('targets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_targets_account_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_targets_account_id'))
        batch_op.drop_column('retry_backoff_seconds')
        batch_op.drop_column('capture_mode')
        batch_op.drop_column('account_id')

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'running', 'success', 'failed', 'skipped', 'suspended', name='runstatus'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('session_status')
        batch_op.drop_column('diagnostic_path')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_status'))
        batch_op.drop_index(batch_op.f('ix_accounts_owner_id'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
