"""schema initial

Revision ID: fcce3f6865c3
Revises: 
Create Date: 2026-07-20 12:19:20.546680
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fcce3f6865c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('run_time', sa.String(length=5), nullable=True),
    sa.Column('cron_expression', sa.String(length=120), nullable=True),
    sa.Column('timezone_name', sa.String(length=64), nullable=True),
    sa.Column('viewport_width', sa.Integer(), nullable=True),
    sa.Column('viewport_height', sa.Integer(), nullable=True),
    sa.Column('full_page', sa.Boolean(), nullable=False),
    sa.Column('wait_until', sa.String(length=20), nullable=False),
    sa.Column('wait_after_load_ms', sa.Integer(), nullable=True),
    sa.Column('timeout_ms', sa.Integer(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('locale', sa.String(length=20), nullable=True),
    sa.Column('hide_selectors', sa.Text(), nullable=True),
    sa.Column('dismiss_selectors', sa.Text(), nullable=True),
    sa.Column('storage_state_json', sa.Text(), nullable=True),
    sa.Column('session_profile', sa.String(length=64), nullable=True),
    sa.Column('expected_selector', sa.Text(), nullable=True),
    sa.Column('fail_if_url_contains', sa.Text(), nullable=True),
    sa.Column('subfolder', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', 'skipped', name='runstatus'), nullable=False),
    sa.Column('trigger', sa.Enum('scheduled', 'manual', name='triggertype'), nullable=False),
    sa.Column('capture_date', sa.String(length=10), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('screenshot_path', sa.Text(), nullable=True),
    sa.Column('screenshot_bytes', sa.Integer(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('page_title', sa.Text(), nullable=True),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('drive_folder_id', sa.String(length=120), nullable=True),
    sa.Column('drive_file_id', sa.String(length=120), nullable=True),
    sa.Column('drive_file_link', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('skipped_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_runs_idempotency_key')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_capture_date'), ['capture_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_content_sha256'), ['content_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_runs_target_id'), ['target_id'], unique=False)

    op.create_table('run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('step', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_run_logs_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_run_logs_run_id'))

    op.drop_table('run_logs')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_target_id'))
        batch_op.drop_index(batch_op.f('ix_runs_status'))
        batch_op.drop_index(batch_op.f('ix_runs_content_sha256'))
        batch_op.drop_index(batch_op.f('ix_runs_capture_date'))

    op.drop_table('runs')
    op.drop_table('targets')
    # ### end Alembic commands ###
